name: test

on: [push, workflow_dispatch]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Git and Pip
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        python -m pip install --upgrade pip
        python -m pip install wheel
        git --version
        python --version
    - name: Install miniver
      run: |
        pip install .
    - name: Set up minimal python packages
      run: |
        cd ..
        # simple package
        python miniver/ci/create_package.py simple-distr simple_pkg
        # simple package in 'src' layout
        python miniver/ci/create_package.py simple-src-distr simple_src_pkg --src-layout
        # namespace package
        python miniver/ci/create_package.py ns-distr nspkg.simple_pkg
        # namespace package in 'src' layout
        python miniver/ci/create_package.py ns-src-distr nspkg.simple_src_pkg --src-layout
    - name: Test versioning of simple package
      shell: bash
      run: cd .. && miniver/ci/test_package.sh simple-distr simple_pkg
    - name: Test versioning of simple src-layout package
      shell: bash
      run: cd .. && miniver/ci/test_package.sh simple-src-distr simple_src_pkg
    - name: Test versioning of namespace package
      shell: bash
      run: cd .. && miniver/ci/test_package.sh ns-distr nspkg.simple_pkg
    - name: Test versioning of namespace src-layout package
      shell: bash
      run: cd .. && miniver/ci/test_package.sh ns-src-distr nspkg.simple_src_pkg
